import { Project } from '../models/project';
export let projectsList: Project[] = [{
    _id: '0',
    active: true,
    country: 'Burkina Faso',
    countryImage: 'assets/images/burkina-flag.png',
    name: 'Test in Burkina Faso',
    themes: ['SSR'],
    start: new Date('2019-08-01'),
    end: new Date('2022-05-31'),
    inputDate: null
},
{
    _id: '1',
    active: true,
    country: 'Burkina Faso',
    countryImage: 'assets/images/burkina-flag.png',
    name: 'Test in Burkina Faso',
    themes: ['CrCo', 'SSR'],
    start: new Date('2019-05-01'),
    end: new Date('2022-05-31'),
    inputDate: null
},
{
    _id: '2',
    active: true,
    country: 'Burkina Faso',
    countryImage: 'assets/images/burkina-flag.png',
    name: 'Atelier centre paris',
    themes: ['SSR'],
    start: new Date('2019-05-01'),
    end: new Date('2022-05-31'),
    inputDate: null
},
{
    _id: '3',
    active: true,
    country: 'Burkina Faso',
    countryImage: 'assets/images/burkina-flag.png',
    name: 'Atelier centre paris',
    themes: ['SSR'],
    start: new Date('2019-05-01'),
    end: new Date('2022-05-31'),
    inputDate: new Date('2019-05-20T11:05:51.710Z')
},
{
    _id: '4',
    active: true,
    country: 'Burkina Faso',
    countryImage: 'assets/images/burkina-flag.png',
    name: 'Atelier centre paris',
    themes: ['SSR'],
    start: new Date('2019-05-01'),
    end: new Date('2022-05-31'),
    inputDate: new Date('2019-05-20T11:05:51.710Z')
},
{
    _id: '5',
    active: true,
    country: 'Burkina Faso',
    countryImage: 'assets/images/burkina-flag.png',
    name: 'Atelier centre paris',
    themes: ['SSR'],
    start: new Date('2019-05-01'),
    end: new Date('2022-05-31'),
    inputDate: null
},
{
    _id: '6',
    active: true,
    country: 'Burkina Faso',
    countryImage: 'assets/images/burkina-flag.png',
    name: 'Atelier centre paris',
    themes: ['SSR'],
    start: new Date('2019-05-01'),
    end: new Date('2022-05-31'),
    inputDate: new Date('2019-05-20T11:05:51.710Z')
},
{
    _id: '7',
    active: true,
    country: 'Burkina Faso',
    countryImage: 'assets/images/burkina-flag.png',
    name: 'Atelier centre paris',
    themes: ['SSR'],
    start: new Date('2019-05-01'),
    end: new Date('2022-05-31'),
    inputDate: null
},
{
    _id: '8',
    active: true,
    country: 'Burkina Faso',
    countryImage: 'assets/images/burkina-flag.png',
    name: 'Atelier centre paris',
    themes: ['SSR'],
    start: new Date('2019-05-01'),
    end: new Date('2022-05-31'),
    inputDate: null
},
{
    _id: '9',
    active: true,
    country: 'Burkina Faso',
    countryImage: 'assets/images/burkina-flag.png',
    name: 'Atelier centre paris',
    themes: ['SSR'],
    start: new Date('2019-05-01'),
    end: new Date('2020-05-31'),
    inputDate: null
},
{
    _id: '10',
    active: true,
    country: 'Italie',
    countryImage: 'assets/images/italy-flag.png',
    name: 'Atelier centre paris',
    themes: ['SSR'],
    start: new Date('2019-05-01'),
    end: new Date('2020-05-31'),
    inputDate: null
},
{
    _id: '11',
    active: true,
    country: 'Italie',
    countryImage: 'assets/images/italy-flag.png',
    name: 'Atelier centre paris',
    themes: ['SSR'],
    start: new Date('2019-05-01'),
    end: new Date('2020-05-31'),
    inputDate: null
},
{
    _id: '12',
    active: true,
    country: 'Italie',
    countryImage: 'assets/images/italy-flag.png',
    name: 'Atelier centre paris',
    themes: ['SSR'],
    start: new Date('2019-05-01'),
    end: new Date('2020-05-31'),
    inputDate: null
},
{
    _id: '13',
    active: true,
    country: 'Italie',
    countryImage: 'assets/images/italy-flag.png',
    name: 'Atelier centre paris',
    themes: ['SSR'],
    start: new Date('2019-05-01'),
    end: new Date('2020-05-31'),
    inputDate: null
},
{
    _id: '14',
    active: true,
    country: 'Italie',
    countryImage: 'assets/images/italy-flag.png',
    name: 'Atelier centre paris',
    themes: ['SSR'],
    start: new Date('2019-05-01'),
    end: new Date('2022-05-31'),
    inputDate: new Date('2019-05-20T11:05:51.710Z')
},
{
    _id: '15',
    active: true,
    country: 'Italie',
    countryImage: 'assets/images/italy-flag.png',
    name: 'Atelier centre paris',
    themes: ['SSR'],
    start: new Date('2019-05-01'),
    end: new Date('2022-05-31'),
    inputDate: null
},
{
    _id: '16',
    active: true,
    country: 'Italie',
    countryImage: 'assets/images/italy-flag.png',
    name: 'Atelier centre paris',
    themes: ['SSR'],
    start: new Date('2019-05-01'),
    end: new Date('2022-05-31'),
    inputDate: new Date('2019-05-20T11:05:51.710Z')
},
{
    _id: '17',
    active: true,
    country: 'Italie',
    countryImage: 'assets/images/italy-flag.png',
    name: 'Atelier centre paris',
    themes: ['SSR'],
    start: new Date('2019-05-01'),
    end: new Date('2022-05-31'),
    inputDate: null
},
{
    _id: '18',
    active: true,
    country: 'Italie',
    countryImage: 'assets/images/italy-flag.png',
    name: 'Atelier centre paris',
    themes: ['SSR'],
    start: new Date('2019-05-01'),
    end: new Date('2022-05-31'),
    inputDate: new Date('2019-05-20T11:05:51.710Z')
},
{
    _id: '19',
    active: true,
    country: 'Italie',
    countryImage: 'assets/images/italy-flag.png',
    name: 'Atelier centre paris',
    themes: ['SSR'],
    start: new Date('2019-05-01'),
    end: new Date('2022-05-31'),
    inputDate: null
},
{
    _id: '20',
    active: false,
    country: 'Inde',
    countryImage: 'assets/images/india-flag.png',
    name: 'Atelier centre paris',
    themes: ['SSR'],
    start: new Date('2019-05-01'),
    end: new Date('2022-05-31'),
    inputDate: null
},
{
    _id: '21',
    active: false,
    country: 'Inde',
    countryImage: 'assets/images/india-flag.png',
    name: 'Atelier centre paris',
    themes: ['SSR'],
    start: new Date('2019-05-01'),
    end: new Date('2022-05-31'),
    inputDate: null
},
{
    _id: '22',
    active: false,
    country: 'Inde',
    countryImage: 'assets/images/india-flag.png',
    name: 'Atelier centre paris',
    themes: ['SSR'],
    start: new Date('2019-05-01'),
    end: new Date('2022-05-31'),
    inputDate: null
},
{
    _id: '23',
    active: false,
    country: 'Inde',
    countryImage: 'assets/images/india-flag.png',
    name: 'Atelier centre paris',
    themes: ['SSR'],
    start: new Date('2019-05-01'),
    end: new Date('2022-05-31'),
    inputDate: null
},
{
    _id: '24',
    active: false,
    country: 'Inde',
    countryImage: 'assets/images/india-flag.png',
    name: 'Atelier centre paris',
    themes: ['SSR'],
    start: new Date('2019-05-01'),
    end: new Date('2022-05-31'),
    inputDate: null
},
{
    _id: '25',
    active: false,
    country: 'Inde',
    countryImage: 'assets/images/india-flag.png',
    name: 'Atelier centre paris',
    themes: ['SSR'],
    start: new Date('2019-05-01'),
    end: new Date('2022-05-31'),
    inputDate: null
},
{
    _id: '26',
    active: false,
    country: 'Inde',
    countryImage: 'assets/images/india-flag.png',
    name: 'Atelier centre paris',
    themes: ['SSR'],
    start: new Date('2019-05-01'),
    end: new Date('2022-05-31'),
    inputDate: null
},
{
    _id: '27',
    active: false,
    country: 'Inde',
    countryImage: 'assets/images/india-flag.png',
    name: 'Atelier centre paris',
    themes: ['SSR'],
    start: new Date('2019-05-01'),
    end: new Date('2022-05-31'),
    inputDate: null
},
{
    _id: '28',
    active: false,
    country: 'Inde',
    countryImage: 'assets/images/india-flag.png',
    name: 'Atelier centre paris',
    themes: ['SSR'],
    start: new Date('2019-05-01'),
    end: new Date('2022-05-31'),
    inputDate: null
},
{
    _id: '29',
    active: false,
    country: 'Inde',
    countryImage: 'assets/images/india-flag.png',
    name: 'Atelier centre paris',
    themes: ['SSR'],
    start: new Date('2019-05-01'),
    end: new Date('2022-05-31'),
    inputDate: null
},
];
